// Ley N° 18 575 - Bases Generales de la Administración del estado (LOCBGAE)
// Texto oficial verificado en BCN / LeyChile.
// "comentarioProfesor" son notas de cátedra basadas en Bermúdez, "Derecho Administrativo General".

const locbgae = [
    {
        numero: 1,
        capitulo: 1,
        capituloTitulo: "Normas Generales",
        titulo: "La Administración del Estado estará constituida por",
        texto: "El Presidente de la República ejerce el gobierno y la administración del Estado con la colaboración de los órganos que establezcan la Constitución y las leyes.\n La Administración del Estado estará constituida por los Ministerios, las Intendencias, las Gobernaciones y los órganos y servicios públicos creados para el cumplimiento de la función administrativa, incluidos la Contraloría General de la República, el Banco Central, las Fuerzas Armadas y las Fuerzas de Orden y Seguridad pública, los Gobiernos Regionales, las Municipalidades y las empresas públicas creadas por ley.",
        conceptos: ["Concepto"],
    },
    {
        numero: 2,
        capitulo: 1,
        capituloTitulo: "Normas Generales",
        titulo: "Los órganos de la Administración del Estado someterán su acción a la Constitución y a las leyes.",
        texto: "Los órganos de la Administración del Estado someterán su acción a la Constitución y a las leyes. Deberán actuar dentro de su competencia y no tendrán más atribuciones que las que expresamente les haya conferido el ordenamiento jurídico. Todo abuso o exceso en el ejercicio de sus potestades dará lugar a las acciones y recursos correspondientes.",
        conceptos: ["."],
    },
    {
        numero: 3,
        capitulo: 1,
        capituloTitulo: "Normas Generales",
        titulo: "La Administración del Estado está al servicio de la persona humana",
        texto: "La Administración del Estado está al servicio de la persona humana; su finalidad es promover el bien común atendiendo las necesidades públicas en forma continua y permanente y fomentando el desarrollo del país a través del ejercicio de las atribuciones que le confiere la Constitución y la ley, y de la aprobación, ejecución y control de políticas, planes, programas y acciones de alcance nacional, regional y comunal.\nLa Administración del Estado deberá observar los principios de responsabilidad, eficiencia, eficacia, coordinación, impulsión de oficio del procedimiento, impugnabilidad de los actos administrativos, control, probidad, transparencia y publicidad administrativas, y garantizará la debida autonomía de los grupos intermedios de la sociedad para cumplir sus propios fines específicos, respetando el derecho de las personas para realizar cualquier actividad económica, en conformidad con la Constitución Política y las leyes.",
        conceptos: ["."],
    },
    {
        numero: 4,
        capitulo: 1,
        capituloTitulo: "Normas Generales",
        titulo: "El Estado será responsable.",
        texto: "El Estado será responsable por los daños que causen los órganos de la Administración en el ejercicio de sus funciones, sin perjuicio de las responsabilidades que pudieren afectar al funcionario que los hubiere ocasionado.",
        conceptos: ["."],
    },
    {
        numero: 5,
        capitulo: 1,
        capituloTitulo: "Normas Generales",
        titulo: "Las autoridades y funcionarios.",
        texto: " Las autoridades y funcionarios deberán velar por la eficiente e idónea administración de los medios públicos y por el debido cumplimiento de la función pública.\nLos órganos de la Administración del Estado deberán cumplir sus cometidos coordinadamente y propender a la unidad de acción, evitando la duplicación o interferencia de funciones.",
        conceptos: ["."],
    },
    {
        numero: 6,
        capitulo: 1,
        capituloTitulo: "Normas Generales",
        titulo: "El Estado podrá",
        texto: "El Estado podrá participar y tener representación en entidades que no formen parte de su Administración sólo en virtud de una ley que lo autorice, la que deberá ser de quórum calificado si esas entidades desarrollan actividades empresariales.\nLas entidades a que se refiere el inciso anterior no podrán, en caso alguno, ejercer potestades públicas.",
        conceptos: ["."],
    },
    {
        numero: 7,
        capitulo: 1,
        capituloTitulo: "Normas Generales",
        titulo: "Los funcionarios",
        texto: "Los funcionarios de la Administración del Estado estarán afectos a un régimen jerarquizado y disciplinado. Deberán cumplir fiel y esmeradamente sus obligaciones para con el servicio y obedecer las órdenes que les imparta el superior jerárquico.",
        conceptos: ["."],
    },
    {
        numero: 8,
        capitulo: 1,
        capituloTitulo: "Normas Generales",
        titulo: "Los órganos de la Administración",
        texto: "Los órganos de la Administración del Estado actuarán por propia iniciativa en el cumplimiento de sus funciones, o a petición de parte cuando la ley lo exija expresamente o se haga uso del derecho de petición o reclamo, procurando la simplificación y rapidez de los trámites.\nLos procedimientos administrativos deberán ser ágiles y expeditos, sin más formalidades que las que establezcan las leyes y reglamentos.",
        conceptos: ["."],
    },
    {
        numero: "8 Bis",
        capitulo: 1,
        capituloTitulo: "Normas Generales",
        titulo: "Los contratos administrativos",
        texto: "Los contratos administrativos se celebrarán previa propuesta pública, en conformidad a la ley.\nEl procedimiento concursal se regirá por los principios de libre concurrencia de los oferentes al llamado administrativo y de igualdad ante las bases que rigen el contrato.\nLa licitación privada procederá, en su caso, previa resolución fundada que así lo disponga, salvo que por la naturaleza de la negociación corresponda acudir al trato directo.",
        conceptos: ["."],
    },
    {
        numero: 9,
        capitulo: 1,
        capituloTitulo: "Normas Generales",
        titulo: "Los actos administrativos serán impugnables",
        texto: "Los actos administrativos serán impugnables mediante los recursos que establezca la ley. Se podrá siempre interponer el de reposición ante el mismo órgano del que hubiere emanado el acto respectivo y, cuando proceda, el recurso jerárquico, ante el superior correspondiente, sin perjuicio de las acciones jurisdiccionales a que haya lugar.",
        conceptos: ["."],
    },
    {
        numero: 10,
        capitulo: 1,
        capituloTitulo: "Normas Generales",
        titulo: "Las autoridades y jefaturas",
        texto: "Las autoridades y jefaturas, dentro del ámbito de su competencia y en los niveles que corresponda, ejercerán un control jerárquico permanente del funcionamiento de los organismos y de la actuación del personal de su dependencia.\nEste control se extenderá tanto a la eficiencia y eficacia en el cumplimiento de los fines y objetivos establecidos, como a la legalidad y oportunidad de las actuaciones.",
        conceptos: ["."],
    },
    {
        numero: 11,
        capitulo: 1,
        capituloTitulo: "Normas Generales",
        titulo: "Las autoridades y funcionarios",
        texto: "Las autoridades y funcionarios facultados para elaborar planes o dictar normas, deberán velar permanentemente por el cumplimiento de aquéllos y la aplicación de éstas, dentro del ámbito de sus atribuciones, sin perjuicio de las obligaciones propias del personal de su dependencia.",
        conceptos: ["."],
    },
    {
        numero: "11 Bis",
        capitulo: 1,
        capituloTitulo: "Normas Generales",
        titulo: "Los funcionarios de la Administración del Estado deberán",
        texto: "Los funcionarios de la Administración del Estado deberán observar el principio de probidad administrativa y, en particular, las normas legales generales y especiales que lo regulan.\nLa función pública se ejercerá con transparencia, de manera que permita y promueva el conocimiento de los procedimientos, contenidos y fundamentos de las decisiones que se adopten en ejercicio de ella.\nSon públicos los actos administrativos de los órganos de la Administración del Estado y los documentos que les sirvan de sustento o complemento directo y esencial.\nLa publicidad a que se refiere el inciso anterior se extiende a los informes y antecedentes que las empresas privadas que presten servicios de utilidad pública y las empresas a que se refieren los incisos tercero y quinto del artículo 37 de la ley Nº 18.046, sobre Sociedades Anónimas, proporcionen a las entidades estatales encargadas de su fiscalización, en la medida que sean de interés público, que su difusión no afecte el debido funcionamiento de la empresa y que el titular de dicha información no haga uso de su derecho a denegar el acceso a la misma, conforme a lo establecido en los incisos siguientes.\nEn caso de que la información referida en los incisos anteriores no se encuentre a disposición del público de modo permanente, el interesado tendrá derecho a requerirla por escrito al jefe del servicio respectivo.\nCuando el requerimiento se refiera a documentos o antecedentes que contengan información que pueda afectar los derechos o intereses de terceros, el jefe superior del órgano requerido, dentro del plazo de cuarenta y ocho horas, deberá comunicar mediante carta certificada, a la o las personas a que se refiere o afecta la información correspondiente, la facultad que les asiste para oponerse a la entrega de los documentos solicitados, adjuntando copia del requerimiento respectivo.\nLos terceros interesados podrán ejercer su derecho de oposición dentro del plazo de tres días hábiles contado desde la fecha de notificación, la cual se entenderá practicada al tercer día de despachada la correspondiente carta certificada. La oposición deberá presentarse por escrito y no requerirá expresión de causa.\nDeducida la oposición en tiempo y forma, el órgano requerido quedará impedido de proporcionar la documentación o antecedentes solicitados, salvo resolución judicial en contrario, dictada conforme al procedimiento que establece el artículo siguiente. En caso de no deducirse la oposición, se entenderá que el tercero afectado accede a la publicidad de dicha información, a menos que el jefe superior requerido estime fundadamente que la divulgación de la información involucrada afecta sensiblemente los derechos o intereses de los terceros titulares de la misma.\nEl jefe superior del órgano requerido deberá pronunciarse sobre la petición, sea entregando la documentación solicitada o negándose a ello, dentro del plazo de cuarenta y ocho horas contado desde la formulación del requerimiento, o desde la expiración del plazo concedido al tercero afectado, en el caso previsto en el inciso séptimo.\nEl jefe superior del órgano requerido deberá proporcionar la documentación que se les solicite, salvo que concurra alguna de las causales que establece el inciso siguiente, que le autorizan a negarse. En este caso, su negativa a entregar la documentación deberá formularse por escrito y fundadamente, especificando las razones que en cada caso motiven su decisión.\nLas únicas causales en cuya virtud se podrá denegar la entrega de los documentos o antecedentes requeridos son la reserva o secreto establecidos en disposiciones legales o reglamentarias; el que la publicidad impida o entorpezca el debido cumplimiento de las funciones del órgano requerido; la oposición deducida en tiempo y forma por los terceros a quienes se refiere o afecta la información contenida en los documentos requeridos; el que la divulgación o entrega de los documentos o antecedentes requeridos afecte sensiblemente los derechos o intereses de terceras personas, según calificación fundada efectuada por el jefe superior del órgano requerido, y el que la publicidad afecte la seguridad de la Nación o el interés nacional.\nUno o más reglamentos establecerán los casos de secreto o reserva de la documentación y antecedentes que obren en poder de los órganos de la Administración del Estado.",
        conceptos: ["."],
    },
    {
        numero: "11 Ter",
        capitulo: 1,
        capituloTitulo: "Normas Generales",
        titulo: "Vencido el plazo",
        texto: "Vencido el plazo previsto en el artículo anterior para la entrega de la documentación requerida, o denegada la petición por una causa distinta de la seguridad de la Nación o el interés nacional, el requirente tendrá derecho a recurrir al juez de letras en lo civil del domicilio del órgano de la Administración requerido, que se encuentre de turno según las reglas correspondientes, solicitando amparo al derecho consagrado en el artículo precedente.\nEl procedimiento se sujetará a las reglas siguientes:",
        conceptos: ["."],
    },
];
