// Ley N° 18 575 - Bases Generales de la Administración del estado (LOCBGAE)
// Texto oficial verificado en BCN / LeyChile.
// "comentarioProfesor" son notas de cátedra basadas en Bermúdez, "Derecho Administrativo General".

const locbgae = [
    {
        numero: 1,
        capitulo: 1,
        capituloTitulo: "Normas Generales",
        titulo: "La Administración del Estado estará constituida por",
        texto: "El Presidente de la República ejerce el gobierno y la administración del Estado con la colaboración de los órganos que establezcan la Constitución y las leyes.\n La Administración del Estado estará constituida por los Ministerios, las Intendencias, las Gobernaciones y los órganos y servicios públicos creados para el cumplimiento de la función administrativa, incluidos la Contraloría General de la República, el Banco Central, las Fuerzas Armadas y las Fuerzas de Orden y Seguridad pública, los Gobiernos Regionales, las Municipalidades y las empresas públicas creadas por ley.",
        conceptos: ["Concepto"],
    },
    {
        numero: 2,
        capitulo: 1,
        capituloTitulo: "Normas Generales",
        titulo: "Los órganos de la Administración del Estado someterán su acción a la Constitución y a las leyes.",
        texto: "Los órganos de la Administración del Estado someterán su acción a la Constitución y a las leyes. Deberán actuar dentro de su competencia y no tendrán más atribuciones que las que expresamente les haya conferido el ordenamiento jurídico. Todo abuso o exceso en el ejercicio de sus potestades dará lugar a las acciones y recursos correspondientes.",
        conceptos: ["."],
    },
    {
        numero: 3,
        capitulo: 1,
        capituloTitulo: "Normas Generales",
        titulo: "La Administración del Estado está al servicio de la persona humana",
        texto: "La Administración del Estado está al servicio de la persona humana; su finalidad es promover el bien común atendiendo las necesidades públicas en forma continua y permanente y fomentando el desarrollo del país a través del ejercicio de las atribuciones que le confiere la Constitución y la ley, y de la aprobación, ejecución y control de políticas, planes, programas y acciones de alcance nacional, regional y comunal.\nLa Administración del Estado deberá observar los principios de responsabilidad, eficiencia, eficacia, coordinación, impulsión de oficio del procedimiento, impugnabilidad de los actos administrativos, control, probidad, transparencia y publicidad administrativas, y garantizará la debida autonomía de los grupos intermedios de la sociedad para cumplir sus propios fines específicos, respetando el derecho de las personas para realizar cualquier actividad económica, en conformidad con la Constitución Política y las leyes.",
        conceptos: ["."],
    },
    {
        numero: 4,
        capitulo: 1,
        capituloTitulo: "Normas Generales",
        titulo: "El Estado será responsable.",
        texto: "El Estado será responsable por los daños que causen los órganos de la Administración en el ejercicio de sus funciones, sin perjuicio de las responsabilidades que pudieren afectar al funcionario que los hubiere ocasionado.",
        conceptos: ["."],
    },
    {
        numero: 5,
        capitulo: 1,
        capituloTitulo: "Normas Generales",
        titulo: "Las autoridades y funcionarios.",
        texto: " Las autoridades y funcionarios deberán velar por la eficiente e idónea administración de los medios públicos y por el debido cumplimiento de la función pública.\nLos órganos de la Administración del Estado deberán cumplir sus cometidos coordinadamente y propender a la unidad de acción, evitando la duplicación o interferencia de funciones.",
        conceptos: ["."],
    },
    {
        numero: 6,
        capitulo: 1,
        capituloTitulo: "Normas Generales",
        titulo: "El Estado podrá",
        texto: "El Estado podrá participar y tener representación en entidades que no formen parte de su Administración sólo en virtud de una ley que lo autorice, la que deberá ser de quórum calificado si esas entidades desarrollan actividades empresariales.\nLas entidades a que se refiere el inciso anterior no podrán, en caso alguno, ejercer potestades públicas.",
        conceptos: ["."],
    },
    {
        numero: 7,
        capitulo: 1,
        capituloTitulo: "Normas Generales",
        titulo: "Los funcionarios",
        texto: "Los funcionarios de la Administración del Estado estarán afectos a un régimen jerarquizado y disciplinado. Deberán cumplir fiel y esmeradamente sus obligaciones para con el servicio y obedecer las órdenes que les imparta el superior jerárquico.",
        conceptos: ["."],
    },
    {
        numero: 8,
        capitulo: 1,
        capituloTitulo: "Normas Generales",
        titulo: "Los órganos de la Administración",
        texto: "Los órganos de la Administración del Estado actuarán por propia iniciativa en el cumplimiento de sus funciones, o a petición de parte cuando la ley lo exija expresamente o se haga uso del derecho de petición o reclamo, procurando la simplificación y rapidez de los trámites.\nLos procedimientos administrativos deberán ser ágiles y expeditos, sin más formalidades que las que establezcan las leyes y reglamentos.",
        conceptos: ["."],
    },
    {
        numero: "8 Bis",
        capitulo: 1,
        capituloTitulo: "Normas Generales",
        titulo: "Los contratos administrativos",
        texto: "Los contratos administrativos se celebrarán previa propuesta pública, en conformidad a la ley.\nEl procedimiento concursal se regirá por los principios de libre concurrencia de los oferentes al llamado administrativo y de igualdad ante las bases que rigen el contrato.\nLa licitación privada procederá, en su caso, previa resolución fundada que así lo disponga, salvo que por la naturaleza de la negociación corresponda acudir al trato directo.",
        conceptos: ["."],
    },
    {
        numero: 9,
        capitulo: 1,
        capituloTitulo: "Normas Generales",
        titulo: "Los actos administrativos serán impugnables",
        texto: "Los actos administrativos serán impugnables mediante los recursos que establezca la ley. Se podrá siempre interponer el de reposición ante el mismo órgano del que hubiere emanado el acto respectivo y, cuando proceda, el recurso jerárquico, ante el superior correspondiente, sin perjuicio de las acciones jurisdiccionales a que haya lugar.",
        conceptos: ["."],
    },
    {
        numero: 10,
        capitulo: 1,
        capituloTitulo: "Normas Generales",
        titulo: "Las autoridades y jefaturas",
        texto: "Las autoridades y jefaturas, dentro del ámbito de su competencia y en los niveles que corresponda, ejercerán un control jerárquico permanente del funcionamiento de los organismos y de la actuación del personal de su dependencia.\nEste control se extenderá tanto a la eficiencia y eficacia en el cumplimiento de los fines y objetivos establecidos, como a la legalidad y oportunidad de las actuaciones.",
        conceptos: ["."],
    },
    {
        numero: 11,
        capitulo: 1,
        capituloTitulo: "Normas Generales",
        titulo: "Las autoridades y funcionarios",
        texto: "Las autoridades y funcionarios facultados para elaborar planes o dictar normas, deberán velar permanentemente por el cumplimiento de aquéllos y la aplicación de éstas, dentro del ámbito de sus atribuciones, sin perjuicio de las obligaciones propias del personal de su dependencia.",
        conceptos: ["."],
    },
    {
        numero: "11 Bis",
        capitulo: 1,
        capituloTitulo: "Normas Generales",
        titulo: "Los funcionarios de la Administración del Estado deberán",
        texto: "Los funcionarios de la Administración del Estado deberán observar el principio de probidad administrativa y, en particular, las normas legales generales y especiales que lo regulan.\nLa función pública se ejercerá con transparencia, de manera que permita y promueva el conocimiento de los procedimientos, contenidos y fundamentos de las decisiones que se adopten en ejercicio de ella.\nSon públicos los actos administrativos de los órganos de la Administración del Estado y los documentos que les sirvan de sustento o complemento directo y esencial.\nLa publicidad a que se refiere el inciso anterior se extiende a los informes y antecedentes que las empresas privadas que presten servicios de utilidad pública y las empresas a que se refieren los incisos tercero y quinto del artículo 37 de la ley Nº 18.046, sobre Sociedades Anónimas, proporcionen a las entidades estatales encargadas de su fiscalización, en la medida que sean de interés público, que su difusión no afecte el debido funcionamiento de la empresa y que el titular de dicha información no haga uso de su derecho a denegar el acceso a la misma, conforme a lo establecido en los incisos siguientes.\nEn caso de que la información referida en los incisos anteriores no se encuentre a disposición del público de modo permanente, el interesado tendrá derecho a requerirla por escrito al jefe del servicio respectivo.\nCuando el requerimiento se refiera a documentos o antecedentes que contengan información que pueda afectar los derechos o intereses de terceros, el jefe superior del órgano requerido, dentro del plazo de cuarenta y ocho horas, deberá comunicar mediante carta certificada, a la o las personas a que se refiere o afecta la información correspondiente, la facultad que les asiste para oponerse a la entrega de los documentos solicitados, adjuntando copia del requerimiento respectivo.\nLos terceros interesados podrán ejercer su derecho de oposición dentro del plazo de tres días hábiles contado desde la fecha de notificación, la cual se entenderá practicada al tercer día de despachada la correspondiente carta certificada. La oposición deberá presentarse por escrito y no requerirá expresión de causa.\nDeducida la oposición en tiempo y forma, el órgano requerido quedará impedido de proporcionar la documentación o antecedentes solicitados, salvo resolución judicial en contrario, dictada conforme al procedimiento que establece el artículo siguiente. En caso de no deducirse la oposición, se entenderá que el tercero afectado accede a la publicidad de dicha información, a menos que el jefe superior requerido estime fundadamente que la divulgación de la información involucrada afecta sensiblemente los derechos o intereses de los terceros titulares de la misma.\nEl jefe superior del órgano requerido deberá pronunciarse sobre la petición, sea entregando la documentación solicitada o negándose a ello, dentro del plazo de cuarenta y ocho horas contado desde la formulación del requerimiento, o desde la expiración del plazo concedido al tercero afectado, en el caso previsto en el inciso séptimo.\nEl jefe superior del órgano requerido deberá proporcionar la documentación que se les solicite, salvo que concurra alguna de las causales que establece el inciso siguiente, que le autorizan a negarse. En este caso, su negativa a entregar la documentación deberá formularse por escrito y fundadamente, especificando las razones que en cada caso motiven su decisión.\nLas únicas causales en cuya virtud se podrá denegar la entrega de los documentos o antecedentes requeridos son la reserva o secreto establecidos en disposiciones legales o reglamentarias; el que la publicidad impida o entorpezca el debido cumplimiento de las funciones del órgano requerido; la oposición deducida en tiempo y forma por los terceros a quienes se refiere o afecta la información contenida en los documentos requeridos; el que la divulgación o entrega de los documentos o antecedentes requeridos afecte sensiblemente los derechos o intereses de terceras personas, según calificación fundada efectuada por el jefe superior del órgano requerido, y el que la publicidad afecte la seguridad de la Nación o el interés nacional.\nUno o más reglamentos establecerán los casos de secreto o reserva de la documentación y antecedentes que obren en poder de los órganos de la Administración del Estado.",
        conceptos: ["."],
    },
    {
        numero: "11 Ter",
        capitulo: 1,
        capituloTitulo: "Normas Generales",
        titulo: "Vencido el plazo",
        texto: "Vencido el plazo previsto en el artículo anterior para la entrega de la documentación requerida, o denegada la petición por una causa distinta de la seguridad de la Nación o el interés nacional, el requirente tendrá derecho a recurrir al juez de letras en lo civil del domicilio del órgano de la Administración requerido, que se encuentre de turno según las reglas correspondientes, solicitando amparo al derecho consagrado en el artículo precedente.\nEl procedimiento se sujetará a las reglas siguientes:",
        conceptos: ["."],
    },
    {
        numero: "12",
        capitulo: 1,
        capituloTitulo: "Normas Generales",
        titulo: "El personal de la Administración",
        texto: "El personal de la Administración del Estado se regirá por las normas estatutarias que establezca la ley, en las cuales se regulará el ingreso, los deberes y derechos, la responsabilidad administrativa y la cesación de funciones.",
        conceptos: ["."],
    },
    {
        numero: "13",
        capitulo: 1,
        capituloTitulo: "Normas Generales",
        titulo: "Para ingresar a la Administración",
        texto: "Para ingresar a la Administración del Estado se deberá cumplir con los requisitos generales que determine el respectivo estatuto y con los que establece el Título III de esta ley, además de los exigidos para el cargo que se provea.\nTodas las personas que cumplan con los requisitos correspondientes tendrán el derecho de postular en igualdad de condiciones a los empleos de la Administración del Estado, previo concurso.",
        conceptos: ["."],
    },
    {
        numero: "14",
        capitulo: 1,
        capituloTitulo: "Normas Generales",
        titulo: "Las normas estatutarias",
        texto: "Las normas estatutarias del personal de la Administración del Estado deberán proteger la dignidad de la función pública y guardar conformidad con su carácter técnico, profesional y jerarquizado.",
        conceptos: ["."],
    },
    {
        numero: "15",
        capitulo: 1,
        capituloTitulo: "Normas Generales",
        titulo: "El personal de la Administración ",
        texto: "El personal de la Administración del Estado estará sujeto a responsabilidad administrativa, sin perjuicio de la responsabilidad civil y penal que pueda afectarles.\nEn el ejercicio de la potestad disciplinaria se asegurará el derecho a un racional y justo procedimiento.",
        conceptos: ["."],
    },
    {
        numero: "16",
        capitulo: 1,
        capituloTitulo: "Normas Generales",
        titulo: "El personal de la Administración del Estado ",
        texto: "El personal de la Administración del Estado estará impedido de realizar cualquier actividad política dentro de la Administración.",
        conceptos: ["."],
    },
    {
        numero: "17",
        capitulo: 1,
        capituloTitulo: "Normas Generales",
        titulo: "La Administración del Estado",
        texto: "La Administración del Estado asegurará la capacitación y el perfeccionamiento de su personal, conducentes a obtener la formación y los conocimientos necesarios para el desempeño de la función pública.",
        conceptos: ["."],
    },
    {
        numero: "18",
        capitulo: 2,
        capituloTitulo: "Normas Especiales",
        parrafo: "Párrafo 1º",            
        parrafoTitulo: "De la Organización y Funcionamiento", 
        titulo: "La organización básica",
        texto: "La organización básica de los Ministerios, las Intendencias, las Gobernaciones y los servicios públicos creados para el cumplimiento de la función administrativa, será la establecida en este Título.\nLas normas del presente Título no se aplicarán a la Contraloría General de la República, al Banco Central, a las Fuerzas Armadas y a las Fuerzas de Orden y Seguridad Pública, los Gobiernos Regionales, a las Municipalidades, al Consejo Nacional de Televisión y a las empresas públicas creadas por ley, órganos que se regirán por las normas constitucionales pertinentes y por sus respectivas leyes orgánicas constitucionales o de quórum calificado, según corresponda.",
        conceptos: ["."],
    },
    {
        numero: "19",
        capitulo: 2,
        capituloTitulo: "Normas Especiales",
        parrafo: "Párrafo 1º",            
        parrafoTitulo: "De la Organización y Funcionamiento", 
        titulo: "Los Ministerios",
        texto: "Los Ministerios son los órganos superiores de colaboración del Presidente de la República en las funciones de gobierno y administración de sus respectivos sectores, los cuales corresponden a los campos específicos de actividades en que deben ejercer dichas funciones.\nPara tales efectos, deberán proponer y evaluar las políticas y planes correspondientes, estudiar y proponer las normas aplicables a los sectores a su cargo, velar por el cumplimiento de las normas dictadas, asignar recursos y fiscalizar las actividades del respectivo sector.\nEn circunstancias excepcionales, la ley podrá encomendar alguna de las funciones señaladas en el inciso anterior a los servicios públicos. Asimismo, en los casos calificados que determine la ley, un ministerio podrá actuar como órgano administrativo de ejecución.",
        conceptos: ["."],
    },
    {
        numero: "20",
        capitulo: 2,
        capituloTitulo: "Normas Especiales",
        parrafo: "Párrafo 1º",            
        parrafoTitulo: "De la Organización y Funcionamiento", 
        titulo: "Los Ministros de Estado",
        texto: "Los Ministros de Estado, en su calidad de colaboradores directos e inmediatos del Presidente de la República, tendrán la responsabilidad de la conducción de sus respectivos Ministerios, en conformidad con las políticas e instrucciones que aquél imparta.\nEl Presidente de la República podrá encomendar a uno o más Ministros la coordinación de la labor que corresponde a los Secretarios de Estado y las relaciones del Gobierno con el Congreso Nacional.",
        conceptos: ["."],
    },
    {
        numero: "21",
        capitulo: 2,
        capituloTitulo: "Normas Especiales",
        parrafo: "Párrafo 1º",            
        parrafoTitulo: "De la Organización y Funcionamiento", 
        titulo: "En cada Ministerio",
        texto: "En cada Ministerio habrá una o más Subsecretarías, cuyos jefes superiores serán los Subsecretarios, quienes tendrán el carácter de colaboradores inmediatos de los Ministros. Les corresponderá coordinar la acción de los órganos y servicios públicos del sector, actuar como ministros de fe, ejercer la administración interna del Ministerio y cumplir las demás funciones que les señale la ley.",
        conceptos: ["."],
    },
    {
        numero: "22",
        capitulo: 2,
        capituloTitulo: "Normas Especiales",
        parrafo: "Párrafo 1º",            
        parrafoTitulo: "De la Organización y Funcionamiento", 
        titulo: "El Ministro será",
        texto: "El Ministro será subrogado por el respectivo Subsecretario y, en caso de existir más de uno, por el de más antigua designación; salvo que el Presidente de la República nombre a otro Secretario de Estado o que la ley establezca para Ministerios determinados otra forma de subrogación.",
        conceptos: ["."],
    },
    {
        numero: "23",
        capitulo: 2,
        capituloTitulo: "Normas Especiales",
        parrafo: "Párrafo 1º",            
        parrafoTitulo: "De la Organización y Funcionamiento", 
        titulo: "Los Ministerios",
        texto: "Los Ministerios, con las excepciones que contemple la ley, se desconcentrarán territorialmente mediante Secretarías Regionales Ministeriales, las que estarán a cargo de un Secretario Regional Ministerial, quien representará al Ministerio en la respectiva región y será designado oyéndose al Intendente.",
        conceptos: ["."],
    },
    {
        numero: "24",
        capitulo: 2,
        capituloTitulo: "Normas Especiales",
        parrafo: "Párrafo 1º",            
        parrafoTitulo: "De la Organización y Funcionamiento", 
        titulo: "En la organización de los Ministerios",
        texto: "En la organización de los Ministerios, además de las Subsecretarías y de las Secretarías Regionales Ministeriales, podrán existir sólo los niveles jerárquicos de División, Departamento, Sección y Oficina, considerando la importancia relativa y el volumen de trabajo que signifique la respectiva función\nNo obstante lo dipuesto en el inciso anterior, en circunstancias excepcionales la ley podrá establecer niveles jerárquicos distintos o adicionales, así como denominaciones diferentes..",
        conceptos: ["."],
    },
    {
        numero: "25",
        capitulo: 2,
        capituloTitulo: "Normas Especiales",
        parrafo: "Párrafo 1º",            
        parrafoTitulo: "De la Organización y Funcionamiento", 
        titulo: "Los servicios públicos",
        texto: "Los servicios públicos son órganos administrativos encargados de satisfacer necesidades colectivas, de manera regular y contínua. Estarán sometidos a la dependencia o supervigilancia del Presidente de la República a través de los respectivos Ministerios, cuyas políticas, planes y programas les corresponderá aplicar, sin perjuicio de lo dispuesto en los artículos 19, inciso tercero, y 27.\nLa Ley podrá, excepcionalmente, crear servicios públicos bajo la dependencia o supervigilancia directa del Presidente de la República.",
        conceptos: ["."],
    },
    {
        numero: "26",
        capitulo: 2,
        capituloTitulo: "Normas Especiales",
        parrafo: "Párrafo 1º",            
        parrafoTitulo: "De la Organización y Funcionamiento", 
        titulo: "Los servicios públicos serán centralizados o descentralizados",
        texto: "Los servicios públicos serán centralizados o descentralizados.\nLos servicios centralizados actuarán bajo la personalidad jurídica y con los bienes y recursos del Fisco y estarán sometidos a la dependencia del Presidente de la República, a través del Ministerio correspondiente.\nLos servicios descentralizados actuarán con la personalidad jurídica y el patrimonio propios que la ley les asigne y estarán sometidos a la supervigilancia del Presidente de la República a través del Ministerio respectivo. La descentralización podrá ser funcional o territorial.",
        conceptos: ["."],
    },
    {
        numero: "27",
        capitulo: 2,
        capituloTitulo: "Normas Especiales",
        parrafo: "Párrafo 1º",            
        parrafoTitulo: "De la Organización y Funcionamiento", 
        titulo: "Los servicios públicos centralizados o descentralizados",
        texto: "Los servicios públicos centralizados o descentralizados que se creen para desarrollar su actividad en todo o parte de una región, estarán sometidos, en su caso, a la dependencia o supervigilancia del respectivo Intendente.\nNo obstante lo anterior, esos servicios quedarán sujetos a las políticas nacionales y a las normas técnicas del Ministerio a cargo del sector respectivo.",
        conceptos: ["."],
    },
    {
        numero: "28",
        capitulo: 2,
        capituloTitulo: "Normas Especiales",
        parrafo: "Párrafo 1º",            
        parrafoTitulo: "De la Organización y Funcionamiento", 
        titulo: "Los servicios públicos",
        texto: "Los servicios públicos estarán a cargo de un jefe superior denominado Director, quien será el funcionario de más alta jerarquía dentro del respectivo organismo. Sin embargo, la ley podrá, en casos excepcionales, otorgar a los jefes superiores una denominación distinta.\nA los jefes de servicio les corresponderá dirigir, organizar y administrar el correspondiente servicio; controlarlo y velar por el cumplimiento de sus objetivos; responder de su gestión, y desempeñar las demás funciones que la ley les asigne.\nEn circunstancias excepcionales la ley podrá establecer consejos u órganos colegiados en la estructura de los servicios públicos con las facultades que ésta señale, incluyendo la de dirección superior del servicio.",
        conceptos: ["."],
    },
    {
        numero: "29",
        capitulo: 2,
        capituloTitulo: "Normas Especiales",
        parrafo: "Párrafo 1º",            
        parrafoTitulo: "De la Organización y Funcionamiento", 
        titulo: "En la organización interna",
        texto: "En la organización interna de los servicios públicos sólo podrán establecerse los niveles de Dirección Nacional, Direcciones Regionales, Departamento, Subdepartamento, Sección y Oficina.\nLa organización interna de los servicios públicos que se creen para desarrollar su actividad en todo o parte de una región, podrá considerar solamente los niveles de Dirección, Departamento, Subdepartamento, Sección y Oficina.\nPara la creación de los niveles jerárquicos se considerará la importancia relativa y el volumen de trabajo que signifiquen las respectivas funciones y el ámbito territorial en que actuará el servicio. Las instituciones de Educación Superior de carácter estatal podrán, además, establecer en su organización Facultades, Escuelas, Institutos, Centros de Estudios y otras estructuras necesarias para el cumplimiento de sus fines específicos.\nNo obstante lo dispuesto en los incisos anteriores, en circunstancias excepcionales, la ley podrá establecer niveles jerárquicos distintos o adicionales, así como denominaciones diferentes.",
        conceptos: ["."],
    },
    {
        numero: "30",
        capitulo: 2,
        capituloTitulo: "Normas Especiales",
        parrafo: "Párrafo 1º",            
        parrafoTitulo: "De la Organización y Funcionamiento", 
        titulo: "Sin perjuicio de su dependencia jerárquica general",
        texto: "Sin perjuicio de su dependencia jerárquica general, la ley podrá desconcentrar, territorial y funcionalmente, a determinados órganos.\nLa desconcentración territorial se hará mediante Direcciones Regionales, a cargo de un Director Regional, quien dependerá jerárquicamente del Director Nacional del servicio. No obstante, para los efectos de la ejecución de las políticas, planes y programas de desarrollo regional, estarán subordinados al Intendente a través del respectivo Secretario Regional Ministerial.\nLa desconcentración funcional se realizará mediante la radicación por ley de atribuciones en determinados órganos del respectivo servicio.",
        conceptos: ["."],
    },
    {
        numero: "31",
        capitulo: 2,
        capituloTitulo: "Normas Especiales",
        parrafo: "Párrafo 1º",            
        parrafoTitulo: "De la Organización y Funcionamiento", 
        titulo: "En los casos",
        texto: "En los casos en que la ley confiera competencia exclusiva a los servicios centralizados para la resolución de determinadas materias, el jefe del servicio no quedará subordinado al control jerárquico en cuanto a dicha competencia.\nDel mismo modo, la ley podrá dotar a dichos servicios de recursos especiales o asignarles determinados bienes para el cumplimiento de sus fines propios, sin que ello signifique la constitución de un patrimonio diferente del fiscal.",
        conceptos: ["."],
    },
    {
        numero: "32",
        capitulo: 2,
        capituloTitulo: "Normas Especiales",
        parrafo: "Párrafo 1º",            
        parrafoTitulo: "De la Organización y Funcionamiento", 
        titulo: "El Presidente de la República",
        texto: "El Presidente de la República podrá delegar en forma genérica o específica la representación del Fisco en los jefes superiores de los servicios centralizados, para la ejecución de los actos y celebración de los contratos necesarios para el cumplimiento de los fines propios del respectivo servicio. A proposición del jefe superior, el Presidente de la República podrá delegar esa representación en otros funcionarios del servicio.",
        conceptos: ["."],
    },
    {
        numero: "33",
        capitulo: 2,
        capituloTitulo: "Normas Especiales",
        parrafo: "Párrafo 1º",            
        parrafoTitulo: "De la Organización y Funcionamiento", 
        titulo: "La representación judicial y extrajudicial ",
        texto: "La representación judicial y extrajudicial de los servicios descentralizados corresponderá a los respectivos jefes superiores.",
        conceptos: ["."],
    },
    {
        numero: "34",
        capitulo: 2,
        capituloTitulo: "Normas Especiales",
        parrafo: "Párrafo 1º",            
        parrafoTitulo: "De la Organización y Funcionamiento", 
        titulo: "Los servicios públicos podrán",
        texto: "Los servicios públicos podrán encomendar la ejecución de acciones y entregar la administración de establecimientos o bienes de su propiedad, a las Municipalidades o a entidades de derecho privado, previa autorización otorgada por ley y mediante la celebración de contratos, en los cuales deberá asegurarse el cumplimiento de los objetivos del servicio y el debido resguardo del patrimonio del Estado.",
        conceptos: ["."],
    },
    {
        numero: "35",
        capitulo: 2,
        capituloTitulo: "Normas Especiales",
        parrafo: "Párrafo 1º",            
        parrafoTitulo: "De la Organización y Funcionamiento", 
        titulo: "En aquellos lugares",
        texto: "En aquellos lugares donde no exista un determinado servicio público, las funciones de éste podrán ser asumidas por otro. Para tal efecto, deberá celebrarse un convenio entre los jefes superiores de los servicios, aprobado por decreto supremo suscrito por los Ministros correspondientes. Tratándose de convenios de los servicios a que se refiere el artículo 27, éstos serán aprobados por resolución del respectivo Intendente.",
        conceptos: ["."],
    },
    {
        numero: "36",
        capitulo: 2,
        capituloTitulo: "Normas Especiales",
        parrafo: "Párrafo 1º",            
        parrafoTitulo: "De la Organización y Funcionamiento", 
        titulo: "Las contiendas de competencia",
        texto: "Las contiendas de competencia que surjan entre diversas autoridades administrativas serán resueltas por el superior jerárquico del cual dependan o con el cual se relacionen. Tratándose de autoridades dependientes o vinculadas con distintos Ministerios, decidirán en conjunto los Ministros correspondientes, y si hubiere desacuerdo, resolverá el Presidente de la República.",
        conceptos: ["."],
    },
    {
        numero: "37",
        capitulo: 2,
        capituloTitulo: "Normas Especiales",
        parrafo: "Párrafo 1º",            
        parrafoTitulo: "De la Organización y Funcionamiento", 
        titulo: "El gobierno y la administración",
        texto: "El gobierno y la administración superior de cada región residen en el respectivo Intendente, en su carácter de agente natural e inmediato del Presidente de la República, y serán ejercidos con arreglo a la Constitución, a las leyes y a las órdenes e instrucciones de éste, en los términos establecidos en los artículos siguientes.",
        conceptos: ["."],
    },
    {
        numero: "38",
        capitulo: 2,
        capituloTitulo: "Normas Especiales",
        parrafo: "Párrafo 1º",            
        parrafoTitulo: "De la Organización y Funcionamiento", 
        titulo: "Corresponderá al Intendente",
        texto: "Corresponderá al Intendente formular la política de desarrollo de la respectiva región ajustándose a los planes nacionales; asumir la superior iniciativa y responsabilidad en la ejecución y coordinación de las políticas, planes, programas y proyectos de desarrollo regionales; supervigilar, coordinar y fiscalizar los servicios públicos de la región y, en general, cumplir las demás atribuciones que le encomiende la ley.",
        conceptos: ["."],
    },
    {
        numero: "39",
        capitulo: 2,
        capituloTitulo: "Normas Especiales",
        parrafo: "Párrafo 1º",            
        parrafoTitulo: "De la Organización y Funcionamiento", 
        titulo: "Serán órganos asesores",
        texto: "Serán órganos asesores del Intendente, el Consejo Regional de Desarrollo y los organismos técnicos que señale la ley.\nLos Secretarios Regionales Ministeriales estarán subordinados al Intendente para los efectos del ejercicio de las atribuciones que la ley confiere a éste.",
        conceptos: ["."],
    },
    {
        numero: "40",
        capitulo: 2,
        capituloTitulo: "Normas Especiales",
        parrafo: "Párrafo 1º",            
        parrafoTitulo: "De la Organización y Funcionamiento", 
        titulo: "El gobierno y la administración superior",
        texto: "El gobierno y la administración superior de cada provincia residen en el Gobernador, quien estará subordinado al Intendente respectivo.",
        conceptos: ["."],
    },
    {
        numero: "41",
        capitulo: 2,
        capituloTitulo: "Normas Especiales",
        parrafo: "Párrafo 1º",            
        parrafoTitulo: "De la Organización y Funcionamiento", 
        titulo: "Corresponderá al Gobernador",
        texto: "Corresponderá al Gobernador, de acuerdo con las instrucciones del Intendente, la supervigilancia de los servicios públicos existentes en la provincia, pudiendo representar a aquél las necesidades o deficiencias que observare, y ejercer las demás atribuciones que le encomiende la ley o le delegue el Intendente.\nSin perjuicio de lo anterior, los Gobernadores podrán designar delegados para el ejercicio de sus facultades en una o más localidades, en los casos y formas que determine la ley.",
        conceptos: ["."],
    },
    {
        numero: "42",
        capitulo: 2,
        capituloTitulo: "Normas Especiales",
        parrafo: "Párrafo 1º",            
        parrafoTitulo: "De la Organización y Funcionamiento", 
        titulo: "Los Ministros de Estado y los Subsecretarios",
        texto: "Los Ministros de Estado y los Subsecretarios serán de la exclusiva confianza del Presidente de la República, y requerirán, para su designación, ser chilenos, tener cumplidos veintiún años de edad y reunir los requisitos generales para el ingreso a la Administración Pública.\nLos Intendentes y Gobernadores tendrán, igualmente, la calidad de funcionarios de exclusiva confianza del Presidente de la República, y requerirán para su designación ser ciudadanos con derecho a sufragio y tener los demás requisitos de idoneidad que establezca la ley.\nLos jefes superiores del servicio, con excepción de los rectores de las Instituciones de Educación Superior de carácter estatal, serán de exclusiva confianza del Presidente de la República, y para su designación deberán cumplir con los requisitos generales de ingreso a la Administración Pública, y con los que para casos especiales exijan las leyes.",
        conceptos: ["."],
    },
    {
        numero: "43",
        capitulo: 2,
        capituloTitulo: "Normas Especiales",
        parrafo: "Párrafo 1º",            
        parrafoTitulo: "De la Organización y Funcionamiento", 
        titulo: "El ejercicio de las atribuciones y facultades",
        texto: "El ejercicio de las atribuciones y facultades propias podrá ser delegado, sobre las bases siguientes:",
       numerales: [
        "a. La delegación deberá ser parcial y recaer en materias específicas;",
        "b. Los delegados deberán ser funcionarios de la dependencia de los delegantes;",
        "c. El acto de delegación deberá ser publicado o notificado según corresponda;",
        "d. La responsabilidad por las decisiones administrativas que se adopten o por las actuaciones que se ejecuten recaerá en el delegado, sin perjuicio de la responsabilidad del delegante por negligencia en el cumplimiento de sus obligaciones de dirección o fiscalización, y",
        "e. La delegación será esencialmente revocable.",
      ],
    textoContinuacion: "El delegante no podrá ejercer la competencia delegada sin que previamente revoque la delegación.,\nPodrá, igualmente, delegarse la facultad de firmar, por orden de la autoridad delegante, en determinados actos sobre materias específicas. Esta delegación no modifica la responsabilidad de la autoridad correspondiente, sin perjuicio de la que pudiera afectar al delegado por negligencia en el ejercicio de la facultad delegada.",
    conceptos: ["."],
    },
    {
        numero: "44",
        capitulo: 2,
        capituloTitulo: "Normas Especiales",
        parrafo: "Párrafo 1º",            
        parrafoTitulo: "De la Organización y Funcionamiento", 
        titulo: "Los órganos de la Administración",
        texto: "Los órganos de la Administración serán responsables del daño que causen por falta de servicio.\nNo obstante, el Estado tendrá derecho a repetir en contra del funcionario que hubiere incurrido en falta personal.",
        conceptos: ["."],
    },
    {
        numero: "45",
        capitulo: 2,
        capituloTitulo: "Normas Especiales",
        parrafo: "Párrafo 2º",            
        parrafoTitulo: "De la Carrera Funcionaria", 
        titulo: "El Estatuto Administrativo",
        texto: "El Estatuto Administrativo del personal de los organismos señalados en el inciso primero del artículo 18 regulará la carrera funcionaria y considerará especialmente el ingreso, los deberes y derechos, la responsabilidad administrativa y la cesación de funciones, en conformidad con las bases que se establecen en los artículos siguientes y en el Título III de esta ley. Cuando las características de su ejercicio lo requieran, podrán existir estatutos de carácter especial para determinadas profesiones o actividades.\nEstos estatutos deberán ajustarse, en todo caso, a las disposiciones de este Párrafo.",
        conceptos: ["."],
    },
    {
        numero: "46",
        capitulo: 2,
        capituloTitulo: "Normas Especiales",
        parrafo: "Párrafo 2º",            
        parrafoTitulo: "De la Carrera Funcionaria", 
        titulo: "El ingreso en calidad de titular",
        texto: "El ingreso en calidad de titular se hará por concurso público y la selección de los postulantes se efectuará mediante procedimientos técnicos, imparciales e idóneos que aseguren una apreciación objetiva de sus aptitudes y méritos.",
        conceptos: ["."],
    },
    {
        numero: "47",
        capitulo: 2,
        capituloTitulo: "Normas Especiales",
        parrafo: "Párrafo 2º",            
        parrafoTitulo: "De la Carrera Funcionaria", 
        titulo: "Este personal estará sometido",
        texto: "Este personal estará sometido a un sistema de carrera que proteja la dignidad de la función pública y que guarde conformidad con su carácter técnico, profesional y jerarquizado.\nLa carrera funcionaria será regulada por el respectivo estatuto y se fundará en el mérito, la antigüedad y la idoneidad de los funcionarios, para cuyo efecto existirán procesos de calificación objetivos e imparciales.\nLas promociones deberán efectuarse, según lo disponga el estatuto, por concurso, al que se aplicarán las reglas previstas en el artículo anterior, o por ascenso en el respectivo escalafón.",
        conceptos: ["."],
    },
    {
        numero: "48",
        capitulo: 2,
        capituloTitulo: "Normas Especiales",
        parrafo: "Párrafo 2º",            
        parrafoTitulo: "De la Carrera Funcionaria", 
        titulo: "Asimismo, este personal",
        texto: "Asimismo, este personal gozará de estabilidad en el empleo y sólo podrá cesar en él por renuncia voluntaria debidamente aceptada; por jubilación o por otra causal legal, basada en su desempeño deficiente, en el incumplimiento de sus obligaciones, en la pérdida de requisitos para ejercer la función, en el término del período legal por el cual se es designado o en la supresión del empleo. Lo anterior es sin perjuicio de la facultad que tiene el Presidente de la República o la autoridad llamada a hacer el nombramiento en relación con los cargos de su exclusiva confianza.\nEl desempeño deficiente y el incumplimiento de obligaciones deberá acreditarse en las calificaciones correspondientes o mediante investigación o sumario administrativo.\nLos funcionarios públicos sólo podrán ser destinados a funciones propias del empleo para el cual han sido designados, dentro del órgano o servicio público correspondiente.\nLos funcionarios públicos podrán ser designados en comisiones de servicio para el desempeño de funciones ajenas al cargo, en el mismo órgano o servicio público o en otro distinto, tanto en el territorio nacional como en el extranjero. Las comisiones de servicio serán esencialmente transitorias, y no podrán significar el desempeño de funciones de inferior jerarquía a las del cargo, o ajenas a los conocimientos que éste requiere o al servicio público.",
        conceptos: ["."],
    },
    {
        numero: "49",
        capitulo: 2,
        capituloTitulo: "Normas Especiales",
        parrafo: "Párrafo 2º",            
        parrafoTitulo: "De la Carrera Funcionaria", 
        titulo: "Para los efectos de la calificación",
        texto: "Para los efectos de la calificación del desempeño de los funcionarios públicos, un reglamento establecerá un procedimiento de carácter general, que asegure su objetividad e imparcialidad, sin perjuicio de las reglamentaciones especiales que pudieran dictarse de acuerdo con las características de determinados organismos o servicios públicos. Además, se llevará una hoja de vida por cada funcionario, en la cual se anotarán sus méritos y deficiencias.\nLa calificación se considerará para el ascenso, la eliminación del servicio y los estímulos al funcionario, en la forma que establezca la ley.",
        conceptos: ["."],
    },
    {
        numero: "50",
        capitulo: 2,
        capituloTitulo: "Normas Especiales",
        parrafo: "Párrafo 2º",            
        parrafoTitulo: "De la Carrera Funcionaria", 
        titulo: "La capacitación y el perfeccionamiento ",
        texto: "La capacitación y el perfeccionamiento en el desempeño de la función pública se realizarán mediante un sistema que propenda a estos fines, a través de programas nacionales, regionales o locales.\nEstas actividades podrán llevarse a cabo mediante convenios con instituciones públicas o privadas.\nLa ley podrá exigir como requisito de promoción o ascenso el haber cumplido determinadas actividades de capacitación o perfeccionamiento.\nLa destinación a los cursos de capacitación y perfeccionamiento se efectuará por orden de escalafón o por concurso, según lo determine la ley.\nPodrán otorgarse becas a los funcionarios públicos para seguir cursos relacionados con su capacitación y perfeccionamiento.\nEl presupuesto de la Nación considerará globalmente o por organismo los recursos para los efectos previstos en este artículo.",
        conceptos: ["."],
    },
    {
        numero: "51",
        capitulo: 2,
        capituloTitulo: "Normas Especiales",
        parrafo: "Párrafo 2º",            
        parrafoTitulo: "De la Carrera Funcionaria", 
        titulo: "Sin perjuicio de lo dispuesto",
        texto: "Sin perjuicio de lo dispuesto en los N°s. 9° y 10° del artículo 32 de la Constitución Política de la República, la ley podrá otorgar a determinados empleos la calidad de cargos de la exclusiva confianza del Presidente de la República o de la autoridad facultada para efectuar el nombramiento.\nNo obstante, la ley sólo podrá conferir dicha calidad a empleos que correspondan a los tres primeros niveles jerárquicos del respectivo órgano o servicio. Uno de los niveles jerárquicos corresponderá, en el caso de los Ministerios, a los Secretarios Regionales Ministeriales, y en el caso de los servicios públicos, a los subdirectores y a los directores regionales. Si el respectivo órgano o servicio no contare con los cargos antes mencionados, la ley podrá otorgar la calidad de cargo de la exclusiva confianza, sólo a los empleos que correspondan a los dos primeros niveles jerárquicos. Para estos efectos, no se considerarán los cargos a que se refieren las disposiciones constitucionales citadas en el inciso precedente.\nCon todo, la ley podrá también otorgar la calidad de cargo de la exclusiva confianza a todos aquellos que conforman la planta de personal de la Presidencia de la República.\nSe entenderá por funcionarios de exclusiva confianza aquéllos sujetos a la libre designación y remoción del Presidente de la República o de la autoridad facultada para disponer el nombramiento.",
        conceptos: ["."],
    },
    {
        numero: "52",
        capitulo: 2,
        capituloTitulo: "Normas Especiales",
        parrafo: "Párrafo 2º",            
        parrafoTitulo: "De la Carrera Funcionaria", 
        titulo: "Los regímenes legales de remuneraciones",
        texto: "Los regímenes legales de remuneraciones podrán establecer sistemas o modalidades que estimulen el ejercicio de determinadas funciones por parte de los empleados o premien la idoneidad de su desempeño, sin perjuicio de la aplicación de las escalas generales de sueldos y del principio de que a funciones análogas, que importen responsabilidades semejantes y se ejerzan en condiciones similares, se les asignen iguales retribuciones y demás beneficios económicos.",
        conceptos: ["."],
    },
    {
        numero: "53",
        capitulo: 2,
        capituloTitulo: "Normas Especiales",
        parrafo: "Párrafo 2º",            
        parrafoTitulo: "De la Carrera Funcionaria", 
        titulo: "El Estado velará permanentemente por la carrera funcionaria",
        texto: "El Estado velará permanentemente por la carrera funcionaria y el cumplimiento de las normas y principios de carácter técnico y profesional establecidos en este párrafo, y asegurará tanto la igualdad de oportunidades de ingreso a ella como la capacitación y el perfeccionamiento de sus integrantes.",
        conceptos: ["."],
    },
    {
        numero: "54",
        capitulo: 3,
        capituloTitulo: "De la probidad administrativa",
        parrafo: "Párrafo 1º",            
        parrafoTitulo: "Reglas generales", 
        titulo: "Las autoridades de la Administración del Estado",
        texto: "Las autoridades de la Administración del Estado, cualquiera que sea la denominación con que las designen la Constitución y las leyes, y los funcionarios de la Administración Pública, sean de planta o a contrata, deberán dar estricto cumplimiento al principio de la probidad administrativa.\nEl principio de la probidad administrativa consiste en observar una conducta funcionaria intachable y un desempeño honesto y leal de la función o cargo, con preeminencia del interés general sobre el particular.\nSu inobservancia acarreará las responsabilidades y sanciones que determinen la Constitución, las leyes y el párrafo 4º de este Título, en su caso.",
        conceptos: ["."],
    },
    {
        numero: "55",
        capitulo: 3,
        capituloTitulo: "De la probidad administrativa",
        parrafo: "Párrafo 1º",            
        parrafoTitulo: "Reglas generales", 
        titulo: "El interés general",
        texto: "El interés general exige el empleo de medios idóneos de diagnóstico, decisión y control, para concretar, dentro del orden jurídico, una gestión eficiente y eficaz. Se expresa en el recto y correcto ejercicio del poder público por parte de las autoridades administrativas; en lo razonable e imparcial de sus decisiones; en la rectitud de ejecución de las normas, planes, programas y acciones; en la integridad ética y profesional de la administración de los recursos públicos que se gestionan; en la expedición en el cumplimiento de sus funciones legales, y en el acceso ciudadano a la información administrativa, en conformidad a la ley.",
        conceptos: ["."],
    },
    {
        numero: "56",
        capitulo: 3,
        capituloTitulo: "De la probidad administrativa",
        parrafo: "Párrafo 2º",            
        parrafoTitulo: "De las inhabilidades e incompatibilidades administrativas", 
        titulo: "Sin perjuicio de las inhabilidades especiales",
        texto: "Sin perjuicio de las inhabilidades especiales que establezca la ley, no podrán ingresar a cargos en la Administración del Estado:",
        numerales: [
            "a.Las personas que tengan vigente o suscriban, por sí o por terceros, contratos o cauciones ascendentes a doscientas unidades tributarias mensuales o más, con el respectivo organismo de la Administración Pública.\nTampoco podrán hacerlo quienes tengan litigios pendientes con la institución de que se trata, a menos que se refieran al ejercicio de derechos propios, de su cónyuge, hijos, adoptados o parientes hasta el tercer grado de consanguinidad y segundo de afinidad inclusive.\n Igual prohibición regirá respecto de los directores, administradores, representantes y socios titulares del diez por ciento o más de los derechos de cualquier clase de sociedad, cuando ésta tenga contratos o cauciones vigentes ascendentes a doscientas unidades tributarias mensuales o más, o litigios pendientes, con el organismo de la Administración a cuyo ingreso se postule.",
            "b.Las personas que tengan la calidad de cónyuge, hijos, adoptados o parientes hasta el tercer grado de consanguinidad y segundo de afinidad inclusive respecto de las autoridades y de los funcionarios directivos del organismo de la administración civil del Estado al que postulan, hasta el nivel de jefe de departamento o su equivalente, inclusive.",
            "c.Las personas que se hallen condenadas por crimen o simple delito."
        ],
        conceptos: ["."],
    },
    {
        numero: "57",
        capitulo: 3,
        capituloTitulo: "De la probidad administrativa",
        parrafo: "Párrafo 2º",            
        parrafoTitulo: "De las inhabilidades e incompatibilidades administrativas", 
        titulo: "Para los efectos del artículo anterior",
        texto: "Para los efectos del artículo anterior, los postulantes a un cargo público deberán prestar una declaración jurada que acredite que no se encuentran afectos a alguna de las causales de inhabilidad previstas en ese artículo.",
        conceptos: ["."],
    },
    {
        numero: "58",
        capitulo: 3,
        capituloTitulo: "De la probidad administrativa",
        parrafo: "Párrafo 2º",            
        parrafoTitulo: "De las inhabilidades e incompatibilidades administrativas", 
        titulo: "Todos los funcionarios",
        texto: "Todos los funcionarios tendrán derecho a ejercer libremente cualquier profesión, industria, comercio u oficio conciliable con su posición en la Administración del Estado, siempre que con ello no se perturbe el fiel y oportuno cumplimiento de sus deberes funcionarios, sin perjuicio de las prohibiciones o limitaciones establecidas por ley.\nEstas actividades deberán desarrollarse siempre fuera de la jornada de trabajo y con recursos privados. Son incompatibles con la función pública las actividades particulares cuyo ejercicio deba realizarse en horarios que coincidan total o parcialmente con la jornada de trabajo que se tenga asignada.\nAsimismo, son incompatibles con el ejercicio de la función pública las actividades particulares de las autoridades o funcionarios que se refieran a materias específicas o casos concretos que deban ser analizados, informados o resueltos por ellos o por el organismo o servicio público a que pertenezcan; y la representación de un tercero en acciones civiles deducidas en contra de un organismo de la Administración del Estado, salvo que actúen en favor de alguna de las personas señaladas en la letra b) del artículo 56 o que medie disposición especial de ley que regule dicha representación.\nDel mismo modo son incompatibles las actividades de las ex autoridades o ex funcionarios de una institución fiscalizadora que impliquen una relación laboral con entidades del sector privado sujetas a la fiscalización de ese organismo. Esta incompatibilidad se mantendrá hasta seis meses después de haber expirado en funciones.",
        conceptos: ["."],
    },
];
